[package]
name = "multibam"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-htslib = "0.47.0"
clap = { version = "4.5.4", features = ["derive"] }
rayon = "1.10.0"
indexmap = {version = "2.2.6", features = ["rayon"]}
colored = "2"
