[package]
name = "bam_processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.46.0"
bam = "0.1.4"
indexmap = "2.2.6"
strsim = "0.11.1"
